name : Calculator CI/CD

on:
  push:
    branch :
      -main

  pull_request:
    branches:
      -main

  workflow-dispatch:

  schedule:
    -cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      -name: Checkout Code
       uses: actions/checkout@v4

      -name: Setup Node
       uses: actions/setup-node@v4
       with:
        node-version: 20

      -name: Install Dependencies
       run: npm install

      -name: Run ESLint
       run: npm run lint

      -name: Run Jest Tests
       run: npm test
      
      -name: Build Project
       run: echo "Building Application..."

      -name: Deploy Project
       run: echo "Deploy Succesfully"

  nightly-report:
    runs-on: ubuntu-latest

    if: github.event_name == 'schedule'

    steps:

      -name: Generate report
       run: echo "Generating Report"