name: Calculator CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # --- Task 7: Print Context Data ---
      - name: Show Node Version
        run: node --version

      - name: Show NPM Version
        run: npm --version

      - name: Show Event
        run: echo ${{ github.event_name }}

      - name: Show Date
        run: date

      # --- Project Workflow Steps ---
      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest Tests
        run: npm test
      
      - name: Build Project
        run: echo "Building Application..."

      - name: Deploy Project
        run: echo "Deploy Successfully"

  nightly-report:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Generate report
        run: echo "Generating Report"

  # --- Task 11: Create a Second Job ---
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello Students"